# Generated by Django 5.2.4 on 2025-07-22 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_remove_payment_paystack_reference_payment_tx_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='portal.application'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('APPLICATION_FORM', 'Application Form (Filled)'), ('ADMISSION_LETTER', 'Admission Letter'), ('BLANK_FORM_TEMPLATE', 'Blank Form Template')], max_length=50),
        ),
    ]
