# Generated by Django 5.2.4 on 2025-07-22 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_document_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('APPLICATION_FEE', 'Application Fee'), ('AGENCY_FEE_FULL', 'Agency Fee (Full)'), ('AGENCY_FEE_HALF', 'Agency Fee (Half)'), ('ADMISSION_FEE', 'Admission Fee')], max_length=50),
        ),
    ]
