# Generated by Django 5.2.4 on 2025-07-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_payment_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('APPLICATION_FEE', 'Application Fee'), ('ADMISSION_FEE', 'Admission Fee'), ('AGENCY_FEE_FULL', 'Agency Fee (Full)'), ('AGENCY_FEE_HALF', 'Agency Fee (Half)')], max_length=50),
        ),
    ]
