# Generated by Django 5.2.4 on 2025-07-26 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_application_visa_status_testimonial_visaupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaupdate',
            name='send_email_notification',
            field=models.BooleanField(default=False, help_text='Check this box to send an email notification to the user about this update.'),
        ),
    ]
