# Generated by Django 5.2.4 on 2025-08-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_visaupdate_send_email_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='country_of_interest',
            field=models.CharField(default='London', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(default='admin@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='full_name',
            field=models.CharField(default='Ami', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='phone_number',
            field=models.CharField(default='09030332393', max_length=20),
            preserve_default=False,
        ),
    ]
