# Generated by Django 5.2.4 on 2025-08-14 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_alter_application_country_of_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='country_applying_from',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 8, 14, 0, 8, 30, 443264, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='declaration_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='emergency_contact_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='emergency_contact_number',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='emergency_contact_relationship',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='father_contact',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='father_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='father_occupation',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='gender',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='grade_level',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='guardian_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='guardian_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='how_did_you_hear',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='medical_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='mother_contact',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='mother_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='mother_occupation',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='nationality',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='passport_photograph',
            field=models.ImageField(blank=True, null=True, upload_to='passport_photos/'),
        ),
        migrations.AddField(
            model_name='application',
            name='place_of_birth',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='postal_code',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='preferred_program',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='previous_school',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('PASSPORT_PHOTOGRAPH', 'Passport Photograph'), ('INTERNATIONAL_PASSPORT', 'International Passport'), ('SCHOOL_CERTIFICATE', 'School Certificate (WAEC/NECO)'), ('BIRTH_CERTIFICATE', 'Birth Certificate'), ('FILLED_APPLICATION_FORM', 'Filled Application Form (Step 2)'), ('ADMISSION_LETTER', 'Admission Letter'), ('BLANK_FORM_TEMPLATE', 'Blank Form Template')], max_length=50),
        ),
    ]
