# Generated by Django 5.2.4 on 2025-08-14 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_application_achievements_application_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('processing_fee', models.DecimalField(decimal_places=2, help_text='Total processing fee in USD', max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='passport_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('PASSPORT_PHOTOGRAPH', 'Passport Photograph'), ('INTERNATIONAL_PASSPORT', 'International Passport'), ('SCHOOL_CERTIFICATE', 'School Certificate (WAEC/NECO)'), ('BIRTH_CERTIFICATE', 'Birth Certificate'), ('FILLED_APPLICATION_FORM', 'Filled Application Form (Step 2)'), ('ADMISSION_LETTER', 'Admission Letter'), ('BLANK_FORM_TEMPLATE', 'Blank Form Template'), ('RESUME_CV', 'Resume/CV'), ('WORK_EXPERIENCE_LETTER', 'Work Experience Letter'), ('JOB_OFFER', 'Job Offer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='portal.application'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('APPLICATION_FEE', 'Application Fee'), ('ADMISSION_FEE', 'Admission Fee'), ('AGENCY_FEE_FULL', 'Agency Fee (Full)'), ('AGENCY_FEE_HALF', 'Agency Fee (Half)'), ('WORK_APP_FEE', 'Work Application Fee'), ('WORK_VISA_50_PERCENT', 'Work Visa Fee (50%)'), ('WORK_VISA_25_PERCENT', 'Work Visa Fee (25%)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonial', to='portal.application'),
        ),
        migrations.AlterField(
            model_name='visaupdate',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visa_updates', to='portal.application'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('STUDENT', 'Student'), ('WORKER', 'Worker')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('STEP_1_APPLICATION_FORM', 'Step 1: Application Form'), ('STEP_2_EMPLOYMENT_FORM', 'Step 2: Employment Form & 50% Fee'), ('STEP_3_JOB_OFFER', 'Step 3: Job Offer & Final Fee'), ('STEP_4_VISA_APPLICATION', 'Step 4: Visa Application'), ('COMPLETED', 'Completed')], default='STEP_1_APPLICATION_FORM', max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('passport_number', models.CharField(max_length=100)),
                ('passport_issue_date', models.DateField()),
                ('passport_expiry_date', models.DateField()),
                ('marital_status', models.CharField(max_length=20)),
                ('current_address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=255)),
                ('sponsor', models.CharField(max_length=100)),
                ('applied_before', models.BooleanField(default=False)),
                ('previous_application_details', models.TextField(blank=True)),
                ('highest_qualification', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(max_length=255)),
                ('years_of_experience', models.CharField(max_length=50)),
                ('skills_certifications', models.TextField(blank=True)),
                ('declaration_agreed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='work_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='portal.workapplication'),
        ),
        migrations.AddField(
            model_name='payment',
            name='work_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='portal.workapplication'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='work_application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonial', to='portal.workapplication'),
        ),
        migrations.AddField(
            model_name='visaupdate',
            name='work_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visa_updates', to='portal.workapplication'),
        ),
    ]
