# Generated by Django 5.2.4 on 2025-08-14 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_country_application_passport_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AddField(
            model_name='workapplication',
            name='passport_photograph',
            field=models.ImageField(blank=True, null=True, upload_to='passport_photos/'),
        ),
        migrations.AddField(
            model_name='workapplication',
            name='visa_status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_STARTED', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='passport_expiry_date',
            field=models.DateField(default=datetime.datetime(2025, 8, 14, 22, 3, 37, 329075, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='passport_issue_date',
            field=models.DateField(default=datetime.datetime(2025, 8, 14, 22, 3, 46, 765650, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='passport_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('INTERNATIONAL_PASSPORT', 'International Passport'), ('SCHOOL_CERTIFICATE', 'School Certificate (WAEC/NECO)'), ('BIRTH_CERTIFICATE', 'Birth Certificate'), ('FILLED_APPLICATION_FORM', 'Filled Application Form (Step 2)'), ('ADMISSION_LETTER', 'Admission Letter'), ('BLANK_FORM_TEMPLATE', 'Blank Form Template'), ('RESUME_CV', 'Resume/CV'), ('WORK_EXPERIENCE_LETTER', 'Work Experience Letter'), ('JOB_OFFER', 'Job Offer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('STUDENT_APP_FEE', 'Student Application Fee'), ('ADMISSION_FEE', 'Admission Fee'), ('AGENCY_FEE_FULL', 'Agency Fee (Full)'), ('AGENCY_FEE_HALF', 'Agency Fee (Half)'), ('WORK_APP_FEE', 'Work Application Fee'), ('WORK_VISA_50_PERCENT', 'Work Visa Fee (50%)'), ('WORK_VISA_25_PERCENT', 'Work Visa Fee (25%)')], max_length=50),
        ),
    ]
