# Generated by Django 5.2.4 on 2025-08-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_alter_application_address_alter_application_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('INTERNATIONAL_PASSPORT', 'International Passport'), ('SCHOOL_CERTIFICATE', 'School Certificate (WAEC/NECO)'), ('BIRTH_CERTIFICATE', 'Birth Certificate'), ('FILLED_APPLICATION_FORM', 'Filled Application Form (Step 2)'), ('ADMISSION_LETTER', 'Admission Letter'), ('BLANK_FORM_TEMPLATE', 'Blank Form Template'), ('RESUME_CV', 'Resume/CV'), ('WORK_EXPERIENCE_LETTER', 'Work Experience Letter'), ('JOB_OFFER', 'Job Offer'), ('BLANK_EMPLOYMENT_FORM', 'Blank Employment Form Template')], max_length=50),
        ),
    ]
