# Generated by Django 5.2.4 on 2025-08-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_alter_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workapplication',
            name='job_offer_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('STUDENT_APP_FEE', 'Student Application Fee'), ('ADMISSION_FEE', 'Admission Fee'), ('AGENCY_FEE_FULL', 'Agency Fee (Full)'), ('AGENCY_FEE_HALF', 'Agency Fee (Half)'), ('WORK_APP_FEE', 'Work Application Fee'), ('WORK_VISA_50_PERCENT', 'Work Visa Fee (50%)'), ('WORK_VISA_25_PERCENT', 'Work Visa Fee (25%)'), ('WORK_VISA_REMAINING_25_PERCENT', 'Work Visa Fee (Remaining 25%)')], max_length=50),
        ),
    ]
