# Generated by Django 5.2.4 on 2025-08-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_workapplication_job_offer_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('INTERNATIONAL_PASSPORT', 'International Passport'), ('SCHOOL_CERTIFICATE', 'School Certificate (WAEC/NECO)'), ('BIRTH_CERTIFICATE', 'Birth Certificate'), ('FILLED_APPLICATION_FORM', 'Filled Application Form (Step 2)'), ('ADMISSION_LETTER', 'Admission Letter'), ('BLANK_FORM_TEMPLATE', 'Blank Student Form Template'), ('RESUME_CV', 'Resume/CV'), ('WORK_EXPERIENCE_LETTER', 'Work Experience Letter'), ('JOB_OFFER', 'Job Offer'), ('BLANK_EMPLOYMENT_FORM', 'Blank Employment Form Template')], max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('STUDENT_APP_FEE', 'Student Application Fee'), ('ADMISSION_FEE', 'Admission Fee'), ('AGENCY_FEE_FULL', 'Agency Fee (Full)'), ('AGENCY_FEE_HALF', 'Agency Fee (Half)'), ('WORK_APP_FEE', 'Work Application Fee'), ('WORK_VISA_50_PERCENT', 'Work Visa Fee (50%)'), ('WORK_VISA_25_PERCENT', 'Work Visa Fee (25%)'), ('WORK_VISA_FINAL_50_PERCENT', 'Work Visa Fee (Final 50%)')], max_length=50),
        ),
    ]
