# Generated by Django 5.2.4 on 2025-08-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_alter_payment_purpose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Student Application', 'verbose_name_plural': 'Student Applications'},
        ),
        migrations.AlterModelOptions(
            name='workapplication',
            options={'verbose_name': 'Work Application', 'verbose_name_plural': 'Work Applications'},
        ),
    ]
