# Generated by Django 5.2.4 on 2025-08-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('INTERNATIONAL_PASSPORT', 'International Passport'), ('SCHOOL_CERTIFICATE', 'School Certificate (WAEC/NECO)'), ('BIRTH_CERTIFICATE', 'Birth Certificate'), ('ADMISSION_LETTER', 'Admission Letter'), ('BLANK_ADMISSION_FORM', 'Blank Admission Form'), ('FILLED_ADMISSION_FORM', 'Filled Admission Form'), ('RESUME_CV', 'Resume/CV'), ('WORK_EXPERIENCE_LETTER', 'Work Experience Letter'), ('JOB_OFFER', 'Job Offer'), ('BLANK_EMPLOYMENT_FORM', 'Blank Employment Form'), ('FILLED_EMPLOYMENT_FORM', 'Filled Employment Form')], max_length=50),
        ),
    ]
