# Generated by Django 5.2.4 on 2025-08-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_alter_document_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('STUDENT_APP_FEE', 'Student Application Fee (NGN)'), ('ADMISSION_FEE', 'Student Admission Fee (USD)'), ('AGENCY_FEE', 'Student Agency Fee (USD)'), ('WORK_APP_FEE', 'Work Application Fee (USD)')], max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='custom_admission_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overrides the default admission fee (USD).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='custom_agency_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overrides the default total agency fee (USD).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='custom_application_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overrides the default student application fee (USD).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workapplication',
            name='custom_application_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overrides the default work application fee (USD).', max_digits=10, null=True),
        ),
    ]
