# Generated by Django 5.2.4 on 2025-08-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_feestructure_application_custom_admission_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='fee_type',
            field=models.CharField(choices=[('STUDENT_APP_FEE', 'Student Application Fee (USD)'), ('ADMISSION_FEE', 'Student Admission Fee (USD)'), ('AGENCY_FEE', 'Student Agency Fee (USD)'), ('WORK_APP_FEE', 'Work Application Fee (USD)')], max_length=50, unique=True),
        ),
    ]
